# Generated by Django 3.1.5 on 2021-01-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210127_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.region')),
            ],
            options={
                'db_table': 'subregions',
            },
        ),
        migrations.RemoveField(
            model_name='master',
            name='master_regions',
        ),
        migrations.AlterField(
            model_name='master',
            name='introduction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddField(
            model_name='master',
            name='subregions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.subregion'),
        ),
    ]
