# Generated by Django 3.1.5 on 2021-01-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210128_0453'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subregion',
            table='sub_regions',
        ),
    ]
