# Generated by Django 3.1.5 on 2021-01-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210131_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
