# Generated by Django 3.1.5 on 2021-01-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmastermatch',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.master'),
        ),
        migrations.AddField(
            model_name='requestmastermatch',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='users.gender'),
        ),
        migrations.AddField(
            model_name='request',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.lessontype'),
        ),
        migrations.AddField(
            model_name='request',
            name='master_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_gender', to='users.gender'),
        ),
        migrations.AddField(
            model_name='request',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.region'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='quotationimage',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.requestmastermatch'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pricing_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricingmethod'),
        ),
    ]
