# Generated by Django 3.1.5 on 2021-01-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210126_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='preffered_lesson_day',
            new_name='preferred_lesson_day',
        ),
    ]
