# Generated by Django 3.1.5 on 2021-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210127_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(default='asdf', max_length=2000),
            preserve_default=False,
        ),
    ]
