# Generated by Django 3.1.5 on 2021-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
