# Generated by Django 3.1.5 on 2021-02-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210129_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmastermatch',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
