# Generated by Django 3.1.5 on 2021-02-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210202_0319'),
        ('services', '0007_requestmastermatch_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subregion'),
        ),
    ]
