# Generated by Django 3.1.5 on 2021-02-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210203_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='region',
            new_name='subregion',
        ),
    ]
