# Generated by Django 3.1.5 on 2021-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210203_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='choices',
            field=models.ManyToManyField(through='services.SelectedChoice', to='services.QuestionChoice'),
        ),
    ]
