# Generated by Django 3.1.5 on 2021-02-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_request_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='choices',
            field=models.ManyToManyField(related_name='made_choices', through='services.SelectedChoice', to='services.QuestionChoice'),
        ),
    ]
